# Generated by Django 3.2.7 on 2021-10-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211015_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(choices=[('Female', 'Male'), ('Male', 'Feminino')], max_length=25),
        ),
    ]
