# Generated by Django 3.2.7 on 2021-10-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customers_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
